name: PR

on:
  pull_request:
    branches:
      - "master"

jobs:
  python-dependencies:
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ['3.14', '3.13', '3.12','3.11','3.10']
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@a783c322200f0519c7926aa6faa857c4e23e9263 # v1.4.2
        with:
          version: 2.4.1
          virtualenvs-create: true
      - name: Cache virtualenv
        id: cache-virtualenv
        uses: actions/cache@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6.0.0
        with:
          path: ~/.cache
          key: venv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'
        run: poetry install

  test-unit:
    permissions:
      contents: read
    needs: python-dependencies
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ['3.14', '3.13', '3.12','3.11','3.10']
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@a783c322200f0519c7926aa6faa857c4e23e9263 # v1.4.2
        with:
          version: 2.4.1
          virtualenvs-create: true
      - name: Cache virtualenv
        id: cache-virtualenv
        uses: actions/cache@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6.0.0
        with:
          path: ~/.cache
          key: venv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'
        run: poetry install
      - name: Running unit tests
        run: make test
